version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springdockercontainer
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    networks:
      - app-network
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: container-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: start-dev

networks:
  app-network:
    driver: bridge
